### ISSUE TITLE
Bootstrapping fails with errors

### ISSUE THREAD

**Issue by Th-Pap** [taikoxyz/raiko#138]
[taiko errors.pdf](https://github.com/taikoxyz/raiko/files/15158218/taiko.errors.pdf)

I have been trying to install a prover for sometime now. I am using to sgx machines from OVH: rise-3 and advance-2. Have not succeded yet as during command 'docker compose up init' the system fails with errors. To overcome this I have created this document (attached) which entails all the details and process steps one by one. appreciate your review and recommendations to overcome this challenge. Thank you

**Comment by Th-Pap** [comment]
Hello, appreciate your support. I have two OVH servers waiting to be utilized :) Thanks

**Comment by smtmfft** [comment]
That error high likely means your PCCS conf is incorrect, can you edit the conf & replace the 127.0.0.1 to 0.0.0.0 and try again??
BTW: double check if PCCS docker works before init.

**Comment by Th-Pap** [comment]
Okay so yes this solved the issue and managed to move on to the next step. bootstrap.json is generated | there is an error: "error: There are no available TCS pages left for a new thread. Please try to increase sgx.max_threads in the manifest. The current value is 16". How can this be solved and rerun init?

**Comment by smtmfft** [comment]
you don't need to rerun init, as the bootstrap is generated, you can register your quote to contract & get sgx_id back, then run the raiko to generate the proof.
I did not meet that error, do you have more logs?? Or you can first try increase the max_threads to 24 or even bigger.

**Comment by Th-Pap** [comment]
cd ~/raiko/provers/sgx/config
edit sgx-guest.docker.manifest.template and increase sgx.max_threads = from 16 to 32
and it works
don't have any other logs

**Comment by RogerLamTd** [comment]
@Th-Pap Assuming problem was resolved by increasing number of threads then, feel free to reopen if other issues occur
