### ISSUE TITLE
raiko panicked

### ISSUE THREAD

**Issue by boblekov** [taikoxyz/raiko#158]
### Describe the bug

Good afternoon. Can you tell me how to fix or eliminate this error? The error does not occur often, perhaps once a day on one block. It is solved by restarting raiko.
![image](https://github.com/taikoxyz/raiko/assets/96989524/ed2e81af-c214-4223-b0cc-1d7534207496)
![image1](https://github.com/taikoxyz/raiko/assets/96989524/7bb0b63f-6dcc-4fd4-b72e-2d1a18308d1f)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by zzlnc4** [comment]
I had the same errors on raiko logs and it appears only when the Prover node is getting out of sync, not 100% sure.  I restarted both prover and raiko docker processes/containers and it went away and immediately I am able to submit block proof within 1 minute

**Comment by davidtaikocha** [comment]
> `taiko_client_prover_relayer` send l2 RPC address to Raiko as `http://l2_execution_engine:8545/` or other address you config, but since `taiko_client_prover_relayer` and Raiko may not under the same network, Raiko may not connect to this address. You can set them to use shared docker network, or use specify IP in Raiko's docker-compose.yml like
> 
> ```
>     extra_hosts:
>       - "l2_execution_engine:192.168.1.100"
> ```
> 
> But this way, you cannot change port `:8545`, you need to ensure that port open.

This is the reason.
