### ISSUE TITLE
decode_transactions error: InputTooShort, use empty tx_list

### ISSUE THREAD

**Issue by boblekov** [taikoxyz/raiko#174]
### Describe the bug

Good afternoon, dear taiko team. Can you tell me how to fix this error? It arose after I updated the files today using "git pull". At the same time, everything works as before, but this error has appeared. Thank you.
![image](https://github.com/taikoxyz/raiko/assets/96989524/856b8116-2237-4cd9-8c90-f5852e17ec8e)
![image](https://github.com/taikoxyz/raiko/assets/96989524/33565ca3-095c-45df-b41d-0e2d3903bee0)
![image](https://github.com/taikoxyz/raiko/assets/96989524/bf228d06-d79f-4b2c-be28-ed1eef108bb6)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Brechtpd** [comment]
Ah this is not a real error and part of the normal process of decoding the tx data. While it is a kind of error, it's an error that needs to be handled internally so indeed a bit confusing for people that look at it, we probably shouldn't print it as an error.

**Comment by boblekov** [comment]
Understood, thanks :)
