### ISSUE TITLE
unable to find prover

### ISSUE THREAD

**Issue by Darclindy** [taikoxyz/raiko#181]
### Describe the bug

When I run a proposer node in my servers, I have configed the prover address and set ENABLE_PROPOSER as true in .env;But when I print log, i found that the proposer always report error like:**dial tcp: lookup ethereum-holesky.blockpi.network: i/o timeout;unable to find prover;**

so I want to kown when this scene occur, should I change other prover's IP, or this is a normal condition?

there is my logs:

simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:20:59.191] Start fetching L2 execution engine's transaction pool content filterPoolContent=false lastProposedAt=2024-05-11T01:58:50+0000
simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:20:59.266] Current base fee                         fee=1e-09
simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:21:00.102] Transactions lists count                 count=1
simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:21:00.169] Proposer current pending nonce           nonce=1
simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:21:00.212] Attempting to assign prover              endpoint=http://hekla.stonemac65.xyz:9876 expiry=1,715,395,860 txListHash=01a823..eda0f5 tierFees="[{Tier:100 Fee:+30000000000} {Tier:200 Fee:+30000000000} {Tier:1000 Fee:+0}]"
simple-taiko-node-taiko_client_proposer-1  | WARN [05-11|02:21:00.280] Failed to assign prover                  endpoint=http://hekla.stonemac65.xyz:9876 error="unsuccessful response 422"
simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:21:00.280] Attempting to assign prover              endpoint=http://hekla.stonemac65.xyz:9876 expiry=1,715,395,860 txListHash=01a823..eda0f5 tierFees="[{Tier:100 Fee:+33000000000} {Tier:200 Fee:+33000000000} {Tier:1000 Fee:+0}]"
simple-taiko-node-taiko_client_proposer-1  | WARN [05-11|02:21:00.348] Failed to assign prover                  endpoint=http://hekla.stonemac65.xyz:9876 error="unsuccessful response 422"
simple-taiko-node-taiko_client_proposer-1  | INFO [05-11|02:21:00.348] Attempting to assign prover              endpoint=http://hekla.stonemac65.xyz:9876 expiry=1,715,395,860 txListHash=01a823..eda0f5 tierFees="[{Tier:100 Fee:+39600000000} {Tier:200 Fee:+39600000000} {Tier:1000 Fee:+0}]"
simple-taiko-node-taiko_client_proposer-1  | WARN [05-11|02:21:00.428] Failed to assign prover                  endpoint=http://hekla.stonemac65.xyz:9876 error="unsuccessful response 422"
simple-taiko-node-taiko_client_proposer-1  | WARN [05-11|02:21:00.428] Failed to build TaikoL1.proposeBlock transaction error="unable to find prover"
simple-taiko-node-taiko_client_proposer-1  | ERROR[05-11|02:22:00.172] Failed to wait for new pending transaction error="dial tcp: lookup ethereum-holesky.blockpi.network: i/o timeout"
simple-taiko-node-taiko_client_proposer-1  | ERROR[05-11|02:22:00.172] Proposing operation error                error="unable to find prover"

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by n1khil69** [comment]
Thats due to prover do not have enough tokens to generate proof

**Comment by mratsim** [comment]
I see 2 errors in your log:

```
Failed to assign prover endpoint=http://hekla.stonemac65.xyz:9876/ error="unsuccessful response 422"
```
and
```
simple-taiko-node-taiko_client_proposer-1 | ERROR[05-11|02:22:00.172] Failed to wait for new pending transaction error="dial tcp: lookup ethereum-holesky.blockpi.network: i/o timeout"
```

Since then we've released mainnet, can you comment if things are still wrong and I'll reopen the issue.
