### ISSUE TITLE
A question about a new update.

### ISSUE THREAD

**Issue by boblekov** [taikoxyz/raiko#263]
### Describe the bug

Dear taiko team, the question is as follows. If I change the server, will I be able to use the old wallet address. Provided that I have saved bootstrap.json and priv.key. I was able to do this before, but now you have released a new update and I have this question. Thank you. <3

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by boblekov** [comment]
And some other error in the new files.
![image](https://github.com/taikoxyz/raiko/assets/96989524/8967a73d-6cf5-4e50-a8d9-8c3f876b6af6)

**Comment by boblekov** [comment]
I tried to start the node by saving bootstrap.json and priv.key. But I got such errors. :(

taiko_client_prover_relayer-1  | ERROR[05-27|08:08:33.664] Failed to request proof                  height=229,158 error="failed to get proof, msg: Can not serialize input for SGX io error: Broken pipe (os error 32), output is Ok(Output { status: ExitStatus(unix_wait_status(25856)), stdout: "Starting one shot mode\nthread 'main' panicked at provers/sgx/guest/src/one_shot.rs:122:10:\ncalled Result::unwrap() on an Err value: Application was not bootstrapped or has a deprecated bootstrap.\nnote: run with RUST_BACKTRACE=1 environment variable to display a backtrace\n", stderr: "Gramine is starting. Parsing TOML manifest file, this may take some time...\n-----------------------------------------------------------------------------------------------------------------------\nGramine detected the following insecure configurations:\n\n  - loader.insecureuse_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)\n  - sys.insecureallow_eventfd = true         (host-based eventfd is enabled)\n  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)\n\nGramine will continue application execution, but this configuration must not be used in production!\n-----------------------------------------------------------------------------------------------------------------------\n\n" })" endpoint=htt p://148.113.18.157:8080

![image](https://github.com/taikoxyz/raiko/assets/96989524/2847ff50-bc2f-417a-bca9-3e033b64a73f)

**Comment by smtmfft** [comment]
Yes, new image normally means different mrenclave (kind of a sgx id), so the new raiko can not read the old key by design. 
Please update the sgx instance id. For prover address, you can use the old one, sgx instance has nothing to do with the prover address.

**Comment by boblekov** [comment]
Wow, so in L1_PROVER_PRIVATE_KEY= can I use the old address? I thought they should be the same as what I entered in script/config_dcap_sgx_verifier.sh. Thank you for your help. <3

**Comment by smtmfft** [comment]
Yes, that key is for sending tx, you can keep using it. 
In new raiko, you will have a new bootstrap, no matter who sends this bootstrap onchain, the same L1_PROVER is fine.

**Comment by boblekov** [comment]
Yeah it works :) Thank you, congratulations on the launch! You are the best! <3
