### ISSUE TITLE
error: failed to get `blake3-zkvm` as a dependency of package `sp1-core v0.1.0

### ISSUE THREAD

**Issue by StoneMac65** [taikoxyz/raiko#286]
### Describe the bug

trying to build V1.0.0 but faced this error. tried on 3 different instances and still same issue. apparently
This patch 

`https://github.com/sp1-patches/BLAKE3.git?branch=patch-blake3_zkvm/v.1.0.0#bac2d59f9122b07a4d91475560b4c3214ae62444 `

is no longer available.

tried and built latest Raiko code and bootstrapped but now the issue is attestation fails every time

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by CeciliaZ030** [comment]
check this out lmk if it work :)
https://github.com/taikoxyz/raiko/pull/284#issuecomment-2156687314

**Comment by StoneMac65** [comment]
> check this out lmk if it work :) [#284 (comment)](https://github.com/taikoxyz/raiko/pull/284#issuecomment-2156687314)

Excellent, my both servers are up and running already using docker precompiled image but will ask our testers to try it out. Thanks

**Comment by mratsim** [comment]
Closing as it should be fixed. Feel free to comment if somehow it isn't and we'll investigate.
