### ISSUE TITLE
SGX FMSPC Support 

### ISSUE THREAD

**Issue by smolmike** [taikoxyz/raiko#287]
### Describe the feature request

Greetings. 

I am requesting support for the below hardware in order to be able to run a prover:

SGX-FMSPC: 00706A100000

Hardware: NUC7CJYH

it is on the supported list of hardware here:

https://github.com/ayeks/SGX-hardware#hardware-with-sgx2-support

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by StoneMac65** [comment]
I think you need to provide your bootstrap Quote

**Comment by smolmike** [comment]
> I think you need to provide your bootstrap Quote

Thank you when I ran the command and it asked for the pccs password inside the /tmp/pckid.csv this is what I edited my response with!
