### ISSUE TITLE
RFC: Maintenance & Keeping up with upstream

### ISSUE THREAD

**Issue by mratsim** [taikoxyz/raiko#8]
This issue is to anticipate future maintenance updates.

The current `taiko/unstable` as of https://github.com/taikoxyz/raiko/commit/2f796f93a899985644c0c11b5aaa3156923cca18 (#1) has forked from Risc0/zeth as of commit https://github.com/taikoxyz/raiko/commit/78880e5fbb0aee9be5f4409212d35d10b89c2743 from October 2023.

Upstream has since changed significantly, making rebase/merge likely a chore, and risky as our testnet depends on this.

At the same time @CeciliaZ030 has been working on Powdr support in https://github.com/taikoxyz/raiko/pull/2, in particular by stripping `std` dependencies. 

1. We likely want to upstream the Risc0 with no `std` dependencies, needing to put those in a PR in sync with upstream changed.
2. We likely want to ensure Powdr support uses the latest Risc0, and add John's changes on top.
3. We likely want to create a branch `taiko/a6` that will be **stable** and can be used for the testnet going forward.
4. Cecilia's branch can replace the current `taiko/unstable` when ready.

Did I miss something?

**Comment by pbeza** [comment]
We probably also need to check if there is any [risc0/zeth test suite](https://github.com/risc0/zeth/blob/main/.github/workflows/ci.yml) and how it works with [raiko](https://github.com/taikoxyz/raiko). AFAIK, we haven't implemented any automated tests yet and I expect Risc0 will want to have some basic test coverage to keep our code maintainable.

**Comment by dyxushuai** [comment]
I suggested to Cecilia that she push a pull request upstream to replace `std` with `no_std`. This will allow us to easily solve the conflict problems for both `raiko` and `powdr`.

**Comment by johntaiko** [comment]
I suggested to Cecilia that she push a pull request upstream to replace `std` with `no_std`. This will allow us to easily solve the conflict problems for both `raiko` and `powdr`.

**Comment by johntaiko** [comment]
Because it's not easy to cherry-pick the changes of `raiko` to the newest code of `zeth`

**Comment by johntaiko** [comment]
> Cecilia's branch can replace the current taiko/unstable when ready.

And what is the standard of "ready", because we need people to ensure it works well in the whole devnet and testnet, keep debugging and keep updating of raiko
